
all:
	+@make -C crt all
	+@make -C sysmem all
	+@make -C test all


clean:
	+@make -C crt clean
	+@make -C sysmem clean
	+@make -C test clean


distclean:
	+@make -C crt distclean
	+@make -C sysmem distclean
	+@make -C test distclean
