#include <api/io.idl>
#include <api/poll.idl>
#include <api/pipe.idl>
#include <api/file.idl>
#include <api/dev.idl>

interface ChrdevImpl: Sneks::IO, Sneks::Poll, Sneks::Pipe, Sneks::File, Sneks::DeviceControl {
	/* horse piss! */
};
