#include <api/io.idl>
#include <api/proc.idl>
#include <api/path.idl>
#include <api/file.idl>
#include <api/namespace.idl>
#include <sys/abend.idl>

/* root's initial console. not for consumption outside the root task. will be
 * replaced once actual ttyS0 etc. terminal selection stuff is available.
 */
interface BootCon: Sneks::IO {
	/* nothing here but us chickens */
};

/* impl spec for root's uapi server. */
interface RootUapi: Sneks::Proc {
	/* emp-tay */
};

/* root resolver, mount/umount server */
interface RootPath: Sneks::Path, Sneks::Namespace {
	/* void */
};

/* device lookup and spawning server. */
interface RootDevices: Sneks::File {
	/* inherited things only */
};

/* root's service mode. */
interface RootServ: Sneks::Abend {
	/* swirling vapour */
};
