
/* implementation specs for various things which are expected to gain more
 * things as e.g. the root UAPI function grows beyond Sneks::Proc.
 */

#include <api/io.idl>
#include <api/proc.idl>
#include <api/path.idl>
#include <sys/abend.idl>


/* root's initial console. not for consumption outside the root task. will be
 * replaced once actual ttyS0 etc. terminal selection stuff is available.
 */
interface BootCon: Sneks::IO {
	/* nothing here but us chickens */
};


/* impl spec for root's uapi server. */
interface RootUapi: Sneks::Proc, Sneks::Path {
	/* emp-tay */
};


/* root's service mode. */
interface RootServ: Sneks::Abend {
	/* swirling vapour */
};
