
/* implementation spec for fs.squashfs. not for client use. */

#include <api/path.idl>
#include <api/file.idl>
#include <api/io.idl>


interface SquashfsImpl: Sneks::Path, Sneks::File, Sneks::IO
{
	/* nothing extra. */
};
