
#ifndef __POSIXLIKE_IDL__
#define __POSIXLIKE_IDL__

module Posix {

/* TODO: use NegativeReturn, ReplyLabel(1) here once libIDL starts allowing
 * properties on exceptions. until then, muidl recognizes either Posix::Errno
 * or the exception content to the same end.
 */
exception Errno {
	unsigned short errno;
};

/* as in <sys/types.h> */
typedef long id_t;
typedef long off_t;

typedef long mode_t;

};

#endif
