
#ifndef __POSIXLIKE_IDL__
#define __POSIXLIKE_IDL__

module Posix {

/* TODO: use NegativeReturn, ReplyLabel(1) here once libIDL starts allowing
 * properties on exceptions. until then, muidl recognizes either Posix::Errno
 * or the exception content to the same end.
 */
exception Errno {
	unsigned short errno;
};

/* as in <sys/types.h> */
typedef unsigned long id_t;
typedef long pid_t;
typedef long long off_t;
typedef unsigned long ino_t;
typedef long dev_t;
typedef long mode_t;
typedef long nlink_t;
typedef long blksize_t;
typedef long blkcnt_t;

typedef unsigned long long time_t;	/* 2038 robust */

struct timespec {
	time_t tv_sec;
	long tv_nsec;
};

};

#endif
