#ifndef __API_DEV_IDL__
#define __API_DEV_IDL__

#include <muidl.idl>
#include <posixlike.idl>
#include <api/io.idl>

module Sneks {

[StubPrefix(__dev), IfaceLabel(0xe80d)]
interface DeviceControl
{
	typedef unsigned long iocmd;

	[Label(0x1000)]
	void ioctl_void(out long result, in IO::handle handle, in iocmd request)
		raises(Posix::Errno);

	[Label(0x1001)]
	void ioctl_int(out long result, in IO::handle handle, in iocmd request, inout long arg)
		raises(Posix::Errno);
};

};

#endif
