
#ifndef __API_FILE_IDL__
#define __API_FILE_IDL__

#include <muidl.idl>
#include <posixlike.idl>

#include <api/io.idl>
#include <api/path.idl>


module Sneks {

/* regular files and block devices. */
[StubPrefix(__file), IfaceLabel(0xe809)]
interface File
{
	const long SEEK_SET = 0;
	const long SEEK_CUR = 1;
	const long SEEK_END = 2;

	[Label(0x0001)]	/* NOTE: remove when muidl provides label #defs */
	void open(out IO::handle fd,
		in Path::object object, in Path::cookie cookie, in long flags)
		raises(Posix::Errno, muidl::NoReply);

	/* analog of lseek(2). @offset is returned as the new position within
	 * @fd.
	 */
	void seek(in IO::handle fd, inout Posix::off_t offset, in long whence)
		raises(Posix::Errno, muidl::NoReply);

	/* TODO: stat(), fstat() */
};

};

#endif
