
#ifndef __API_PIPE_IDL__
#define __API_PIPE_IDL__

#include <l4x2.idl>
#include <posixlike.idl>

#include <api/io.idl>


module Sneks {

[StubPrefix(__pipe), IfaceLabel(0xe804)]
interface Pipe
{
	/* @flags is undefined and must be 0. */
	void pipe(out IO::handle readside, out IO::handle writeside, in long flags)
		raises(Posix::Errno);
};

};


#endif
