
#ifndef __API_PROC_IDL__
#define __API_PROC_IDL__

#include <muidl.idl>
#include <l4x2.idl>
#include <posixlike.idl>


module Sneks {

[StubPrefix(__proc), IfaceLabel(0xe801)]
interface Proc
{
	void create_thread(out L4X2::ThreadId tid)
		raises(Posix::Errno);

	/* not replied to if successful and @tid is the caller, even if the
	 * message was propagated. @utcb_addr is the raw local form of @tid
	 * as available to the caller.
	 */
	void remove_thread(in L4X2::ThreadId tid, in L4X2::word utcb_addr)
		raises(Posix::Errno, muidl::NoReply);
};


};

#endif
